config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'microposts#home'

  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy, :show, :index,:edit, :update] do
    resources :comments
  end
  resources :microposts,          only: [:home]
  resources :relationships,       only: [:create, :destroy]

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true
  validate  :picture_size

  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy
	
  def home
    @posts = Micropost.paginate(page: params[:page])
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to home_path
    else
    	@feed_items = []
      render 'static_pages/home'
    end
  end

  def show
      @micropost = Micropost.find(params[:id])
      @comment  = @micropost.comments.build
      @comments = @micropost.comments.includes(:user)
      @microposts = Micropost.where.not(id: params[:id]).limit(10)
  end

  def edit
      @micropost = Micropost.find(params[:id])
  end

  def update
      @micropost = Micropost.find(params[:id])
      if @micropost.update_attributes(micropost_params)
        flash[:success] = "Micropost updated"
        redirect_to @micropost
      else
        render 'edit'
      end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private
    def micropost_params
      params.require(:micropost).permit(:title,:content, :picture)
    end
    
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="title"><%= link_to micropost.title,  micropost %></span>
  <span class="content"><%= micropost.content %></span>
  <%= image_tag(micropost.picture.url,:width => "400", :height => "100%")  if micropost.picture? %>
  <span class="timestamp">
    <span class="user"><%= link_to micropost.user.name, micropost.user %></span> posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <div style="float: right">
        <%= link_to "", edit_micropost_path(micropost), :title =>"Edit", :class => "glyphicon glyphicon-pencil"  %>&nbsp;
        <%= link_to "", micropost, method: :delete,
                                         data: { confirm: "You sure?" }, :title =>"Delete", :class => "glyphicon glyphicon-trash", :style=>'color: red' %>
        
      </div>
    <% end %>
  </span>
</li>

app/views/microposts/_post.html.erb
<div class="well">
	<p class="title"><%= link_to @post.title,  @post %></p>
	<i><span class="timestamp">
		<%= link_to @post.user.name, @post.user %> posted <%= time_ago_in_words(@post.created_at) %> ago
	</span></i>
	<p><%= @post.content.truncate(300) %></p>
	  <% if current_user?(@post.user) %>
	  	<i style="float: left">
	  		<%= link_to "Edit", edit_micropost_path(@post),:title =>"Edit",:class => "glyphicon glyphicon-pencil" %>
	  		&nbsp;
        	<%= link_to "Delete", @post, method: :delete,
                                         data: { confirm: "You sure?" }, :title =>"Delete", :class => "glyphicon glyphicon-trash", :style=>'color: red' %>
	  	</i>
	  <% end %>
	<i style="float: right"><%= link_to "Read more",  @post %></i>
</div>

app/views/microposts/edit.html.erb
<% provide(:title, 'Update entry') %>
<h1>Update entry</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@micropost) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :content, "Confirmation" %>
      <%= f.text_area :content, class: 'form-control' %>

      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>

      <%= f.submit "Update", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/microposts/home.html.erb
<% provide(:title, 'Entries') %>
<h1>Entries</h1>
<%= will_paginate @posts %>
<% @posts.each do |post| %>
	<% @post = post %>
	  <%= render "microposts/post" %>
<% end %>
<%= will_paginate @posts %>

app/views/microposts/show.html.erb
<% provide(:title, 'Entry') %>
<div class="row">
	<div class="col-md-8 col-sm-8 col-xs-12">
		<h1 style="text-align: left;"><%= @micropost.title %></h1>
		<span class="timestamp">
			Posted <%= time_ago_in_words(@micropost.created_at) %> ago by <%= link_to @micropost.user.name, @micropost.user %>
		</span>
		<p class="well" style="margin-top: 10px" >
			<%=  @micropost.content %>
			<br>
			<%= image_tag(@micropost.picture.url,:width => "400", :height => "100%")  if @micropost.picture? %>
		</p>
		<% if logged_in? %>
			<h4>Add Comment:</h4>
		    <%= form_for(@comment, remote: true, :url => micropost_comments_path(@micropost)) do |f| %>
		        <%= f.text_area :content, placeholder: "Compose new comment...", class: "form-control", :id => "comment-text-field-id" %>
		        <%= f.submit "Comment", class: "btn btn-primary" %>
		    <% end %>
		<% else %>
			<h4>Login to comment</h4>
		<% end %>
	    <ol class="comments" id="comment_id">
			<% if @comments.any? %>
			    <%= render @comments %>
			<% end %>
		</ol>
	</div>
	<div class="col-md-4 col-sm-4 col-xs-12 microposts">
		<h1>Micropost Feed</h1>
		<% @microposts.each do |post|  %>
				<span class="title" style="padding-left: 60px; font-size: 15px">
					<%= link_to post.title,  post %> posted by <%= link_to post.user.name, post.user %><hr>
				</span>

		<% end %>
	</div>
</div>